spring.application.name=solution_1_nimbuse_jose_jwt
server.address=0.0.0.0
server.port=8000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/java20_jwt
spring.datasource.username=postgres
spring.datasource.password=password
spring.security.user.name=user
spring.security.user.password=password
management.endpoints.web.exposure.include=shutdown,health,metrics,info
management.info.env.enabled=true
info.app.version=1.0.0
info.app.name=nimbus-jose-jwt
info.app.description=nimbus jose jwt and spring actuator
server.shutdown=graceful
management.endpoint.env.access=unrestricted 
spring.jpa.hibernate.ddl-auto=update